import { Burger } from './Burger';
import { ComponentSchemaV1 } from '../../types/SchemaV1';
import burgerSourceRaw from './Burger.tsx?raw';

function createRangeControlLayoutProperty(title: string) {
  return {
    type: 'number' as const,
    scope: 'layout' as const,
    title,
    min: 0,
    max: 100,
    display: { type: 'range-control' as const },
  };
}

const textStyleProperties = {
  fontSettings: {
    type: 'object' as const,
    display: { type: 'font-settings-weight', hideLabel: true, useTabDesign: true },
    properties: {
      fontWeight: { type: 'number' as const },
      fontStyle: { type: 'string' as const },
    },
  },
  fontSize: {
    type: 'number' as const,
    display: { type: 'font-size' },
  },
  lineHeight: {
    type: 'number' as const,
    display: { type: 'line-height-input' },
  },
  letterSpacing: {
    type: 'number' as const,
    display: { type: 'letter-spacing-input' },
  },
  wordSpacing: {
    type: 'number' as const,
    display: { type: 'word-spacing-input' },
  },
  textAlign: {
    type: 'string' as const,
    enum: ['left', 'center', 'right', 'justify'],
    display: { type: 'vertical-text-aligh-options' },
  },
  textAppearance: {
    type: 'object' as const,
    display: { type: 'text-appearance', useTabDesign: true },
    properties: {
      textTransform: { type: 'string' as const, enum: ['none', 'uppercase', 'lowercase', 'capitalize'] },
      textDecoration: { type: 'string' as const, enum: ['none', 'underline'] },
      fontVariant: { type: 'string' as const, enum: ['normal', 'small-caps'] },
    },
  },
};

function prefixedTextStyleKey(prefix: 'open' | 'onScroll' | '', name: string) {
  if (!prefix) return name;
  return `${prefix}${name.charAt(0).toUpperCase()}${name.slice(1)}`;
}

function createBurgerTextStyleProperties(prefix: 'open' | 'onScroll' | '') {
  return {
    [prefixedTextStyleKey(prefix, 'fontFamily')]: {
      type: 'string' as const,
      scope: 'common' as const,
      title: '',
      display: { type: 'font-family-select' as const, hideLabel: true, useTabDesign: true },
    },
    [prefixedTextStyleKey(prefix, 'fontSettings')]: {
      ...textStyleProperties.fontSettings,
      scope: 'common' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'fontSize')]: {
      ...textStyleProperties.fontSize,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'lineHeight')]: {
      ...textStyleProperties.lineHeight,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'letterSpacing')]: {
      ...textStyleProperties.letterSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'wordSpacing')]: {
      ...textStyleProperties.wordSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAlign')]: {
      ...textStyleProperties.textAlign,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAppearance')]: {
      ...textStyleProperties.textAppearance,
      scope: 'layout' as const,
      title: '',
    },
  };
}

const closedTextStyleProperties = createBurgerTextStyleProperties('');
const openTextStyleProperties = createBurgerTextStyleProperties('open');
const onScrollTextStyleProperties = createBurgerTextStyleProperties('onScroll');

const closedNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['logoMaxHeight', 'panelHeight'] },
  { type: 'row' as const, items: ['iconSize', 'iconAnimation'] },
  'navTextWidth',
  'fontFamily',
  'fontSettings',
  { type: 'row' as const, items: ['fontSize', 'lineHeight', 'letterSpacing', 'wordSpacing'] },
  'textAlign',
  'textAppearance',
  'navGap',
  'navPaddingLeft',
  'navPaddingRight',
];

const onScrollNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['onScrollLogoMaxHeight', 'onScrollPanelHeight'] },
  { type: 'row' as const, items: ['onScrollIconSize', 'onScrollIconAnimation'] },
  'onScrollNavTextWidth',
  'onScrollFontFamily',
  'onScrollFontSettings',
  { type: 'row' as const, items: ['onScrollFontSize', 'onScrollLineHeight', 'onScrollLetterSpacing', 'onScrollWordSpacing'] },
  'onScrollTextAlign',
  'onScrollTextAppearance',
  'onScrollNavGap',
  'onScrollNavPaddingLeft',
  'onScrollNavPaddingRight',
];

const openNavStateLayout = [
  '__componentName__',
  'type',
  { type: 'row' as const, items: ['menuWidth'] },
  { type: 'row' as const, items: ['textWidth'] },
  'effect',
  'position',
  { type: 'row' as const, items: ['horizontalAlign', 'verticalAlign'] },
  'textOrientation',
  'openFontFamily',
  'openFontSettings',
  { type: 'row' as const, items: ['openFontSize', 'openLineHeight', 'openLetterSpacing', 'openWordSpacing'] },
  'openTextAlign',
  'openTextAppearance',
];

const defaultTextAppearance = {
  textTransform: 'none',
  textDecoration: 'none',
  fontVariant: 'normal',
};

const defaultFontSettings = {
  fontWeight: 400,
  fontStyle: 'normal',
};

const POSITION_VALUES = [
  'left-top',
  'center-top',
  'right-top',
  'left-center',
  'center-center',
  'right-center',
  'left-bottom',
  'center-bottom',
  'right-bottom',
] as const;

const paletteBookmarkItems = [
  'iconColor',
  'closeButtonColor',
  'linkColor',
  'panelColor',
] as const;

const schema = {
  type: 'object',
  version: 1,
  settings: {
    sizing: 'auto manual',
    properties: {
      type: {
        type: 'string',
        scope: 'layout',
        title: '',
        display: { type: 'radio-group' },
        enum: ['a', 'b', 'c'],
      },
      link: {
        type: 'array',
        scope: 'common',
        display: { type: 'page-url-link' },
        items: {
          type: 'object',
          properties: {
            mode: { type: 'string', enum: ['page', 'url'] },
            page: { type: 'string' },
            url: { type: 'string', message: 'Paste URL here...' },
            label: { type: 'string' },
            anchor: { type: 'string' },
            openIn: { type: 'string' },
            showIn: { type: 'string', enum: ['always', 'open only', 'open and compact'] },
          },
        },
      },
      socialLink: {
        type: 'array',
        scope: 'common',
        display: { type: 'url-list' },
        items: {
          type: 'string',
          message: 'Paste URL here...',
        },
      },
      logo: {
        type: 'object',
        scope: 'common',
        title: 'Logo',
        display: { type: 'button-icon-switch' },
        properties: {
          mode: {
            type: 'string',
            enum: ['On', 'Off'],
          },
          icon: {
            type: ['string', 'null'] as const,
            title: 'Logo',
            display: { type: 'settings-image-input' },
          },
        },
      },
      logoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Logo Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      panelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      panelColor: {
        type: 'string',
        scope: 'common',
        title: 'Panel',
        display: { type: 'palette-color-picker' },
      },
      iconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon',
        display: { type: 'palette-color-picker' },
      },
      iconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Icon size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      iconAnimation: {
        type: 'string',
        scope: 'layout',
        title: 'Icon animation',
        display: { type: 'toggle-cycle', enum: ['a'] },
      },
      linkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Default',
        titleByState: {
          default: 'Link Default',
          hover: 'Link Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      onScrollIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon',
        display: { type: 'palette-color-picker' },
      },
      onScrollCloseButtonColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon close',
        display: { type: 'palette-color-picker' },
      },
      onScrollLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Scroll',
        titleByState: {
          onScroll: 'Link Scroll',
          'onScroll-hover': 'Link Scroll Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      onScrollPanelColor: {
        type: 'string',
        scope: 'common',
        title: 'Panel',
        display: { type: 'palette-color-picker' },
      },
      openLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Open',
        titleByState: {
          open: 'Link Open',
          'open-hover': 'Link Open Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      socialIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Social Default',
        titleByState: {
          default: 'Social Default',
          hover: 'Social Hover',
          onScroll: 'Social Scroll',
          'onScroll-hover': 'Social Scroll Hover',
          open: 'Social Open',
          'open-hover': 'Social Open Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      menuBackgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'Menu BG',
        display: { type: 'palette-color-picker' },
      },
      overlayColor: {
        type: 'string',
        scope: 'common',
        title: 'Overlay',
        display: { type: 'palette-color-picker' },
      },
      closeButtonColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon close',
        display: { type: 'palette-color-picker' },
      },
      effect: {
        type: 'string',
        scope: 'layout',
        title: 'Effect',
        display: { type: 'toggle-cycle', enum: ['fade', 'left', 'top', 'right', 'bottom'] },
      },
      menuWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Menu width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      textWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Open text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      navTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Closed text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      position: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: [...POSITION_VALUES] },
      },
      horizontalAlign: {
        type: 'string',
        scope: 'layout',
        title: 'Align',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      verticalAlign: {
        type: 'string',
        scope: 'layout',
        title: 'Align',
        display: { type: 'toggle-cycle', enum: ['top', 'center', 'bottom'] },
      },
      textOrientation: {
        type: 'string',
        scope: 'layout',
        title: 'Text',
        display: { type: 'toggle-cycle', enum: ['vertical', 'horizontal'] },
      },
      stateOverrides: {
        type: 'object',
        scope: 'common',
      },
      gap: createRangeControlLayoutProperty('Gap'),
      navGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      textPaddingLeft: createRangeControlLayoutProperty('Text padding left'),
      textPaddingRight: createRangeControlLayoutProperty('Text padding right'),
      textPaddingTop: createRangeControlLayoutProperty('Text padding top'),
      textPaddingBottom: createRangeControlLayoutProperty('Text padding bottom'),
      onScrollLogoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Logo Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      onScrollPanelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      onScrollIconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Icon size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      onScrollIconAnimation: {
        type: 'string',
        scope: 'layout',
        title: 'Icon animation',
        display: { type: 'toggle-cycle', enum: ['a'] },
      },
      onScrollNavTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Closed text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      onScrollNavGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      onScrollNavPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      onScrollNavPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      ...closedTextStyleProperties,
      ...openTextStyleProperties,
      ...onScrollTextStyleProperties,
    },
    defaults: {
      link: [
        { mode: 'page', page: '', url: '', label: 'Home', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'Works', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'About', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'Contact', anchor: '', openIn: 'Same Tab', showIn: 'always' },
      ],
      socialLink: ['', '', '', ''],
      logo: {
        mode: 'On',
        icon: null,
      },
      panelColor: '#ffffff',
      iconColor: '#000000',
      linkColor: '#000000',
      openLinkColor: '#000000',
      onScrollIconColor: '#000000',
      onScrollCloseButtonColor: '#000000',
      onScrollLinkColor: '#000000',
      onScrollPanelColor: '#ffffff',
      socialIconColor: '#000000',
      menuBackgroundColor: '#ffffff',
      overlayColor: 'rgba(0, 0, 0, 0.45)',
      closeButtonColor: '#000000',
      effect: 'fade',
      iconAnimation: 'a',
      position: 'left-top',
      textOrientation: 'vertical',
      fontFamily: 'Goudy Bookletter 1911',
      fontSettings: defaultFontSettings,
      textAlign: 'left',
      openFontFamily: 'Goudy Bookletter 1911',
      openFontSettings: defaultFontSettings,
      openTextAlign: 'left',
      onScrollIconAnimation: 'a',
      onScrollFontFamily: 'Goudy Bookletter 1911',
      onScrollFontSettings: defaultFontSettings,
      onScrollTextAlign: 'left',
      stateOverrides: {
        hover: {
          linkColor: '#666666',
          socialIconColor: '#666666',
        },
      },
    },
    displayRules: [
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.onScrollLogoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'a' },
        then: { name: 'properties.menuWidth.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'a' },
        then: { name: 'properties.horizontalAlign.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'a' },
        then: { name: 'properties.verticalAlign.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'c', isNotEqual: true },
        then: { name: 'properties.textOrientation.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'c' },
        then: { name: 'properties.textOrientation.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'a', isNotEqual: true },
        then: { name: 'properties.effect.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'b' },
        then: { name: 'properties.horizontalAlign.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'b' },
        then: { name: 'properties.verticalAlign.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'c' },
        then: { name: 'properties.verticalAlign.display.visible', value: false },
      },
      {
        if: { name: 'type', value: 'c' },
        then: { name: 'properties.horizontalAlign.display.visible', value: false },
      },
    ],
    layoutDefaults: {
      m: {
        type: 'b',
        position: 'left-top',
        panelHeight: 56 / 375,
        logoMaxHeight: 80 / 375,
        iconSize: 16 / 375,
        menuWidth: 280 / 375,
        textWidth: 240 / 375,
        navTextWidth: 120 / 375,
        gap: 24 / 375,
        navGap: 24 / 375,
        navPaddingLeft: 10 / 375,
        navPaddingRight: 10 / 375,
        textPaddingLeft: 10 / 375,
        textPaddingRight: 10 / 375,
        textPaddingTop: 10 / 375,
        textPaddingBottom: 10 / 375,
        fontSize: 16 / 375,
        lineHeight: 20 / 375,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 16 / 375,
        openLineHeight: 20 / 375,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        onScrollPanelHeight: 56 / 375,
        onScrollLogoMaxHeight: 80 / 375,
        onScrollIconSize: 16 / 375,
        onScrollNavTextWidth: 120 / 375,
        onScrollNavGap: 24 / 375,
        onScrollNavPaddingLeft: 10 / 375,
        onScrollNavPaddingRight: 10 / 375,
        onScrollFontSize: 16 / 375,
        onScrollLineHeight: 20 / 375,
        onScrollLetterSpacing: 0,
        onScrollWordSpacing: 0,
        onScrollTextAppearance: defaultTextAppearance,
      },
      t: {
        type: 'b',
        position: 'left-top',
        panelHeight: 60 / 768,
        logoMaxHeight: 100 / 768,
        iconSize: 16 / 768,
        menuWidth: 300 / 768,
        textWidth: 260 / 768,
        navTextWidth: 140 / 768,
        gap: 32 / 768,
        navGap: 32 / 768,
        navPaddingLeft: 10 / 768,
        navPaddingRight: 10 / 768,
        textPaddingLeft: 10 / 768,
        textPaddingRight: 10 / 768,
        textPaddingTop: 10 / 768,
        textPaddingBottom: 10 / 768,
        fontSize: 16 / 768,
        lineHeight: 20 / 768,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 16 / 768,
        openLineHeight: 20 / 768,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        onScrollPanelHeight: 60 / 768,
        onScrollLogoMaxHeight: 100 / 768,
        onScrollIconSize: 16 / 768,
        onScrollNavTextWidth: 140 / 768,
        onScrollNavGap: 32 / 768,
        onScrollNavPaddingLeft: 10 / 768,
        onScrollNavPaddingRight: 10 / 768,
        onScrollFontSize: 16 / 768,
        onScrollLineHeight: 20 / 768,
        onScrollLetterSpacing: 0,
        onScrollWordSpacing: 0,
        onScrollTextAppearance: defaultTextAppearance,
      },
      d: {
        type: 'b',
        position: 'left-top',
        panelHeight: 40 / 1440,
        logoMaxHeight: 120 / 1440,
        iconSize: 16 / 1440,
        menuWidth: 320 / 1440,
        textWidth: 60 / 1440,
        navTextWidth: 60 / 1440,
        gap: 12 / 1440,
        navGap: 12 / 1440,
        navPaddingLeft: 10 / 1440,
        navPaddingRight: 10 / 1440,
        textPaddingLeft: 10 / 1440,
        textPaddingRight: 10 / 1440,
        textPaddingTop: 10 / 1440,
        textPaddingBottom: 10 / 1440,
        fontSize: 16 / 1440,
        lineHeight: 16 / 1440,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        textAlign: 'center',
        openFontSize: 16 / 1440,
        openLineHeight: 16 / 1440,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        openTextAlign: 'center',
        onScrollPanelHeight: 40 / 1440,
        onScrollLogoMaxHeight: 120 / 1440,
        onScrollIconSize: 16 / 1440,
        onScrollNavTextWidth: 60 / 1440,
        onScrollNavGap: 12 / 1440,
        onScrollNavPaddingLeft: 10 / 1440,
        onScrollNavPaddingRight: 10 / 1440,
        onScrollFontSize: 16 / 1440,
        onScrollLineHeight: 16 / 1440,
        onScrollLetterSpacing: 0,
        onScrollWordSpacing: 0,
        onScrollTextAppearance: defaultTextAppearance,
        onScrollTextAlign: 'center',
      },
    },
    layout: [
      '__componentName__',
      'type',
      'link',
      'socialLink',
      'logo',
      'logoMaxHeight',
      'panelHeight',
      'panelColor',
      'iconColor',
      'iconSize',
      'iconAnimation',
      'linkColor',
      'openLinkColor',
      'onScrollIconColor',
      'onScrollCloseButtonColor',
      'onScrollLinkColor',
      'onScrollPanelColor',
      'onScrollLogoMaxHeight',
      'onScrollPanelHeight',
      'onScrollIconSize',
      'onScrollIconAnimation',
      'onScrollNavTextWidth',
      'onScrollNavGap',
      'onScrollNavPaddingLeft',
      'onScrollNavPaddingRight',
      'onScrollFontFamily',
      'onScrollFontSettings',
      'onScrollFontSize',
      'onScrollLineHeight',
      'onScrollLetterSpacing',
      'onScrollWordSpacing',
      'onScrollTextAlign',
      'onScrollTextAppearance',
      'socialIconColor',
      'menuBackgroundColor',
      'overlayColor',
      'closeButtonColor',
      'effect',
      'menuWidth',
      'textWidth',
      'navTextWidth',
      'position',
      'horizontalAlign',
      'verticalAlign',
      'textOrientation',
      'gap',
      'navGap',
      'navPaddingLeft',
      'navPaddingRight',
      'textPaddingLeft',
      'textPaddingRight',
      'textPaddingTop',
      'textPaddingBottom',
      'fontFamily',
      'fontSettings',
      'fontSize',
      'lineHeight',
      'letterSpacing',
      'wordSpacing',
      'textAlign',
      'textAppearance',
      'openFontFamily',
      'openFontSettings',
      'openFontSize',
      'openLineHeight',
      'openLetterSpacing',
      'openWordSpacing',
      'openTextAlign',
      'openTextAppearance',
    ],
  },
  panels: [
    {
      id: 'general',
      icon: 'settings',
      title: 'General',
      tooltip: 'General Settings',
      layout: [
        '__componentName__',
        'logo',
      ],
    },
    {
      id: 'compact',
      icon: 'layout',
      title: 'Compact',
      tooltip: 'Compact State',
      layout: closedNavStateLayout,
    },
    {
      id: 'onScroll',
      icon: 'transition',
      title: 'On Scroll',
      tooltip: 'On Scroll State',
      layout: onScrollNavStateLayout,
    },
    {
      id: 'open',
      icon: 'layers',
      title: 'Open',
      tooltip: 'Open State',
      layout: openNavStateLayout,
    },
    {
      id: 'links',
      icon: 'target',
      title: 'Links',
      tooltip: 'Links Settings',
      layout: [
        '__componentName__',
        'link',
      ],
    },
    {
      id: 'socialLinks',
      icon: 'target',
      title: 'Social',
      tooltip: 'Social Links',
      layout: [
        '__componentName__',
        'socialLink',
      ],
    },
  ],
  paletteBookmark: {
    items: [...paletteBookmarkItems],
    panelIds: ['compact', 'onScroll', 'open'],
    stateItems: {
      default: ['iconColor', 'closeButtonColor', 'linkColor', 'panelColor'],
      hover: ['linkColor'],
      onScroll: ['onScrollIconColor', 'onScrollCloseButtonColor', 'onScrollLinkColor', 'onScrollPanelColor'],
      'onScroll-hover': ['onScrollLinkColor'],
      open: ['closeButtonColor', 'openLinkColor', 'socialIconColor', 'menuBackgroundColor', 'overlayColor'],
      'open-hover': ['openLinkColor', 'socialIconColor'],
    },
  },
  states: ['default', 'hover'],
  statePanels: ['compact', 'onScroll', 'open'],
} satisfies ComponentSchemaV1;

export const BurgerComponent = {
  element: Burger,
  id: 'burger',
  name: 'Burger',
  category: 'dev',
  version: 1,
  layoutMode: 'navigation' as const,
  defaultSize: {
    d: {
      width: '100%',
      height: 60 / 1440,
    },
    t: {
      width: '100%',
      height: 60 / 768,
    },
    m: {
      width: '100%',
      height: 56 / 375,
    },
  },
  schema,
  sourceCode: burgerSourceRaw,
  assetsPaths: {
    content: [],
    parameters: [{ path: 'logo.icon' }],
  },
  fontSettingsPaths: {
    content: [],
    parameters: [{ path: 'fontFamily' }, { path: 'openFontFamily' }, { path: 'onScrollFontFamily' }],
  },
  fontRelations: {
    fontSettings: 'fontFamily',
    openFontSettings: 'openFontFamily',
    onScrollFontSettings: 'onScrollFontFamily',
  },
};
