import { Burger } from './Burger';
import { ComponentSchemaV1 } from '../../types/SchemaV1';
import burgerSourceRaw from './Burger.tsx?raw';

function createRangeControlLayoutProperty(title: string) {
  return {
    type: 'number' as const,
    scope: 'layout' as const,
    title,
    min: 0,
    max: 100,
    display: { type: 'range-control' as const },
  };
}

const textStyleProperties = {
  fontSettings: {
    type: 'object' as const,
    display: { type: 'font-settings-weight', hideLabel: true, useTabDesign: true },
    properties: {
      fontWeight: { type: 'number' as const },
      fontStyle: { type: 'string' as const },
    },
  },
  fontSize: {
    type: 'number' as const,
    display: { type: 'font-size' },
  },
  lineHeight: {
    type: 'number' as const,
    display: { type: 'line-height-input' },
  },
  letterSpacing: {
    type: 'number' as const,
    display: { type: 'letter-spacing-input' },
  },
  wordSpacing: {
    type: 'number' as const,
    display: { type: 'word-spacing-input' },
  },
  textAlign: {
    type: 'string' as const,
    enum: ['left', 'center', 'right', 'justify'],
    display: { type: 'vertical-text-aligh-options' },
  },
  textAppearance: {
    type: 'object' as const,
    display: { type: 'text-appearance', useTabDesign: true },
    properties: {
      textTransform: { type: 'string' as const, enum: ['none', 'uppercase', 'lowercase', 'capitalize'] },
      textDecoration: { type: 'string' as const, enum: ['none', 'underline'] },
      fontVariant: { type: 'string' as const, enum: ['normal', 'small-caps'] },
    },
  },
};

function prefixedTextStyleKey(prefix: 'open' | 'compact' | '', name: string) {
  if (!prefix) return name;
  return `${prefix}${name.charAt(0).toUpperCase()}${name.slice(1)}`;
}

function createBurgerTextStyleProperties(prefix: 'open' | 'compact' | '') {
  return {
    [prefixedTextStyleKey(prefix, 'fontFamily')]: {
      type: 'string' as const,
      scope: 'common' as const,
      title: '',
      display: { type: 'font-family-select' as const, hideLabel: true, useTabDesign: true },
    },
    [prefixedTextStyleKey(prefix, 'fontSettings')]: {
      ...textStyleProperties.fontSettings,
      scope: 'common' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'fontSize')]: {
      ...textStyleProperties.fontSize,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'lineHeight')]: {
      ...textStyleProperties.lineHeight,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'letterSpacing')]: {
      ...textStyleProperties.letterSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'wordSpacing')]: {
      ...textStyleProperties.wordSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAlign')]: {
      ...textStyleProperties.textAlign,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAppearance')]: {
      ...textStyleProperties.textAppearance,
      scope: 'layout' as const,
      title: '',
    },
  };
}

const closedTextStyleProperties = createBurgerTextStyleProperties('');
const openTextStyleProperties = createBurgerTextStyleProperties('open');
const compactTextStyleProperties = createBurgerTextStyleProperties('compact');

const defaultNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['panelHeight', 'navTextWidth'] },
  { type: 'row' as const, title: '', items: ['navTextPosition', 'navTextOffset'] },
  { type: 'row' as const, title: 'Logo', items: ['logoMaxHeight', 'logoPosition'] },
  { type: 'row' as const, title: 'Hamburger', items: ['iconSize', 'showIcon'] },
  'fontFamily',
  'fontSettings',
  { type: 'row' as const, items: ['fontSize', 'lineHeight', 'letterSpacing', 'wordSpacing'] },
  'textAlign',
  'textAppearance',
  'navGap',
  'navPaddingLeft',
  'navPaddingRight',
];

const compactNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['compactPanelHeight', 'compactNavTextWidth'] },
  { type: 'row' as const, title: '', items: ['compactNavTextPosition', 'compactNavTextOffset'] },
  { type: 'row' as const, title: 'Logo', items: ['compactLogoMaxHeight', 'compactLogoPosition'] },
  { type: 'row' as const, title: 'Hamburger', items: ['compactIconSize', 'compactShowIcon'] },
  'compactFontFamily',
  'compactFontSettings',
  { type: 'row' as const, items: ['compactFontSize', 'compactLineHeight', 'compactLetterSpacing', 'compactWordSpacing'] },
  'compactTextAlign',
  'compactTextAppearance',
  'compactNavGap',
  'compactNavPaddingLeft',
  'compactNavPaddingRight',
];

const openNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, title: 'Text', items: ['textWidth', 'position'] },
  { type: 'row' as const, title: 'Menu', items: ['openPanelSize', 'effect'] },
  'openFontFamily',
  'openFontSettings',
  { type: 'row' as const, items: ['openFontSize', 'openLineHeight', 'openLetterSpacing', 'openWordSpacing'] },
  'openTextAlign',
  'openTextAppearance',
];

const defaultTextAppearance = {
  textTransform: 'none',
  textDecoration: 'none',
  fontVariant: 'normal',
};

const defaultFontSettings = {
  fontWeight: 400,
  fontStyle: 'normal',
};

const defaultShowIn = {
  d: 'Always',
  t: 'Open Only',
  m: 'Open Only',
};

const POSITION_VALUES = [
  'left-top',
  'center-top',
  'right-top',
  'left-center',
  'center',
  'right-center',
  'left-bottom',
  'center-bottom',
  'right-bottom',
] as const;

const paletteBookmarkItems = [
  'iconColor',
  'logoColor',
  'linkColor',
  'backgroundColor',
] as const;

const schema = {
  type: 'object',
  version: 1,
  settings: {
    sizing: 'auto manual',
    properties: {
      link: {
        type: 'array',
        scope: 'common',
        display: { type: 'page-url-link' },
        items: {
          type: 'object',
          properties: {
            link: {
              type: 'object',
              properties: {
                type: { type: 'string', enum: ['url', 'page', 'anchor'] },
                value: { type: 'string', message: 'Paste URL here...' },
                target: { type: 'string', enum: ['blank', 'self'] },
                anchor: { type: 'string' },
              },
            },
            label: { type: 'string' },
            showIn: { type: 'string', scope: 'layout', enum: ['Always', 'Open Only', 'Open and Compact', 'Default and Open', 'Default and Compact'] },
          },
        },
      },
      logo: {
        type: 'object',
        scope: 'common',
        title: 'Logo',
        display: { type: 'button-icon-switch' },
        properties: {
          mode: {
            type: 'string',
            enum: ['On', 'Off'],
          },
          icon: {
            type: ['string', 'null'] as const,
            title: 'Logo',
            display: { type: 'settings-image-input' },
          },
        },
      },
      logoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      logoPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      compactLogoPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      logoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo Default',
        titleByState: {
          default: 'Logo Default',
          hover: 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      panelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Menu Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      backgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'BG Default',
        display: { type: 'palette-color-picker' },
      },
      iconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon Default',
        titleByState: {
          default: 'Icon Default',
          hover: 'Icon Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      showIcon: {
        type: 'string',
        scope: 'layout',
        title: 'Show',
        display: { type: 'toggle-cycle', enum: ['on', 'off'] },
      },
      iconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      linkColor: {
        type: 'string',
        scope: 'common',
        title: 'Text Default',
        titleByState: {
          default: 'Text Default',
          hover: 'Text Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactShowIcon: {
        type: 'string',
        scope: 'layout',
        title: 'Show',
        display: { type: 'toggle-cycle', enum: ['on', 'off'] },
      },
      compactIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon Default',
        titleByState: {
          compact: 'Icon Default',
          'compact-hover': 'Icon Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Text Default',
        titleByState: {
          compact: 'Text Default',
          'compact-hover': 'Text Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactLogoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo Default',
        titleByState: {
          compact: 'Logo Default',
          'compact-hover': 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactBackgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'BG Default',
        display: { type: 'palette-color-picker' },
      },
      openLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Text Default',
        titleByState: {
          open: 'Text Default',
          'open-hover': 'Text Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      openLogoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo Default',
        titleByState: {
          open: 'Logo Default',
          'open-hover': 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      menuBackgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'BG Default',
        display: { type: 'palette-color-picker' },
      },
      overlayColor: {
        type: 'string',
        scope: 'common',
        title: 'Overlay Default',
        display: { type: 'palette-color-picker' },
      },
      closeButtonColor: {
        type: 'string',
        scope: 'common',
        title: 'Close Default',
        titleByState: {
          open: 'Close Default',
          'open-hover': 'Close Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      effect: {
        type: 'string',
        scope: 'layout',
        title: 'Effect',
        display: { type: 'toggle-cycle', enum: ['fade', 'left', 'top', 'right', 'bottom'] },
      },
      openPanelSize: {
        type: 'number',
        scope: 'layout',
        title: 'Height',
        display: { type: 'percentage-input' },
        min: 0,
        max: 100,
      },
      textWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      navTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      navTextPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      navTextOffset: {
        type: 'number',
        scope: 'layout',
        title: 'Offset',
        display: { type: 'numeric-input' },
        min: -9999,
        max: 9999,
      },
      position: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: [...POSITION_VALUES] },
      },
      stateOverrides: {
        type: 'object',
        scope: 'common',
      },
      gap: createRangeControlLayoutProperty('Gap'),
      navGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      textPaddingLeft: createRangeControlLayoutProperty('Text padding left'),
      textPaddingRight: createRangeControlLayoutProperty('Text padding right'),
      textPaddingTop: createRangeControlLayoutProperty('Text padding top'),
      textPaddingBottom: createRangeControlLayoutProperty('Text padding bottom'),
      compactLogoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactPanelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Menu Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactIconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactNavTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactNavTextPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      compactNavTextOffset: {
        type: 'number',
        scope: 'layout',
        title: 'Offset',
        display: { type: 'numeric-input' },
        min: -9999,
        max: 9999,
      },
      compactNavGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      compactNavPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      compactNavPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      ...closedTextStyleProperties,
      ...openTextStyleProperties,
      ...compactTextStyleProperties,
    },
    defaults: {
      link: [
        { link: { type: 'page', value: '', target: 'self' }, label: 'Home', showIn: defaultShowIn },
        { link: { type: 'page', value: '', target: 'self' }, label: 'Works', showIn: defaultShowIn },
        { link: { type: 'page', value: '', target: 'self' }, label: 'About', showIn: defaultShowIn },
        { link: { type: 'page', value: '', target: 'self' }, label: 'Contact', showIn: defaultShowIn },
      ],
      logo: {
        mode: 'On',
        icon: 'https://cdn.cntrl.site/component-assets/hamburger-logo.svg',
      },
      backgroundColor: '#ffffff',
      logoColor: '#000000',
      iconColor: '#000000',
      linkColor: '#000000',
      openLinkColor: '#000000',
      compactIconColor: '#000000',
      compactLinkColor: '#000000',
      compactLogoColor: '#000000',
      compactBackgroundColor: '#ffffff',
      openLogoColor: '#000000',
      menuBackgroundColor: '#ffffff',
      overlayColor: 'rgba(0, 0, 0, 0.45)',
      closeButtonColor: '#000000',
      effect: 'fade',
      showIcon: 'on',
      compactShowIcon: 'on',
      logoPosition: 'left',
      compactLogoPosition: 'left',
      navTextPosition: 'center',
      compactNavTextPosition: 'center',
      navTextOffset: 0,
      compactNavTextOffset: 0,
      position: 'left-top',
      fontFamily: 'Goudy Bookletter 1911',
      fontSettings: defaultFontSettings,
      textAlign: 'left',
      openFontFamily: 'Goudy Bookletter 1911',
      openFontSettings: defaultFontSettings,
      openTextAlign: 'left',
      compactFontFamily: 'Goudy Bookletter 1911',
      compactFontSettings: defaultFontSettings,
      compactTextAlign: 'left',
      stateOverrides: {
        hover: {
          linkColor: '#666666',
          iconColor: '#666666',
          logoColor: '#666666',
        },
        'open-hover': {
          closeButtonColor: '#666666',
        },
      },
    },
    displayRules: [
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoPosition.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoPosition.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoColor.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoColor.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.openLogoColor.display.visible', value: false },
      },
      {
        if: { name: 'effect', value: 'left' },
        then: { name: 'properties.openPanelSize.title', value: 'Width' },
      },
      {
        if: { name: 'effect', value: 'right' },
        then: { name: 'properties.openPanelSize.title', value: 'Width' },
      },
      {
        if: { name: 'showIcon', value: 'off' },
        then: { name: 'properties.iconSize.display.visible', value: false },
      },
      {
        if: { name: 'showIcon', value: 'off' },
        then: { name: 'properties.iconColor.display.visible', value: false },
      },
      {
        if: { name: 'compactShowIcon', value: 'off' },
        then: { name: 'properties.compactIconSize.display.visible', value: false },
      },
      {
        if: { name: 'compactShowIcon', value: 'off' },
        then: { name: 'properties.compactIconColor.display.visible', value: false },
      },
    ],
    layoutDefaults: {
      m: {
        position: 'center',
        panelHeight: 50 / 375,
        logoMaxHeight: 30 / 375,
        logoPosition: 'center',
        compactLogoPosition: 'left',
        navTextPosition: 'center',
        navTextOffset: 0,
        compactNavTextPosition: 'center',
        compactNavTextOffset: 0,
        showIcon: 'on',
        iconSize: 30 / 375,
        textWidth: 240 / 375,
        openPanelSize: 100,
        navTextWidth: 120 / 375,
        gap: 24 / 375,
        navGap: 24 / 375,
        navPaddingLeft: 20 / 375,
        navPaddingRight: 20 / 375,
        textPaddingLeft: 10 / 375,
        textPaddingRight: 10 / 375,
        textPaddingTop: 10 / 375,
        textPaddingBottom: 10 / 375,
        fontSize: 16 / 375,
        lineHeight: 20 / 375,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 34 / 375,
        openLineHeight: 20 / 375,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        openTextAlign: 'center',
        compactPanelHeight: 40 / 375,
        compactLogoMaxHeight: 20 / 375,
        compactShowIcon: 'on',
        compactIconSize: 16 / 375,
        compactNavTextWidth: 80 / 375,
        compactNavGap: 24 / 375,
        compactNavPaddingLeft: 20 / 375,
        compactNavPaddingRight: 20 / 375,
        compactFontSize: 16 / 375,
        compactLineHeight: 20 / 375,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
      },
      t: {
        textAlign: 'center',
        position: 'center',
        panelHeight: 60 / 768,
        logoMaxHeight: 30 / 768,
        logoPosition: 'left',
        compactLogoPosition: 'left',
        navTextPosition: 'center',
        navTextOffset: 0,
        compactNavTextPosition: 'center',
        compactNavTextOffset: 0,
        showIcon: 'on',
        iconSize: 16 / 768,
        textWidth: 300 / 768,
        openPanelSize: 100,
        navTextWidth: 90 / 768,
        gap: 32 / 768,
        navGap: 32 / 768,
        navPaddingLeft: 20 / 768,
        navPaddingRight: 20 / 768,
        textPaddingLeft: 10 / 768,
        textPaddingRight: 10 / 768,
        textPaddingTop: 10 / 768,
        textPaddingBottom: 10 / 768,
        fontSize: 18 / 768,
        lineHeight: 20 / 768,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 75 / 768,
        openLineHeight: 20 / 768,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        openTextAlign: 'center',
        compactTextAlign: 'center',
        compactPanelHeight: 40 / 768,
        compactLogoMaxHeight: 20 / 768,
        compactShowIcon: 'on',
        compactIconSize: 16 / 768,
        compactNavTextWidth: 80 / 768,
        compactNavGap: 32 / 768,
        compactNavPaddingLeft: 20 / 768,
        compactNavPaddingRight: 20 / 768,
        compactFontSize: 16 / 768,
        compactLineHeight: 20 / 768,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
      },
      d: {
        position: 'center',
        panelHeight: 50 / 1440,
        logoMaxHeight: 30 / 1440,
        logoPosition: 'left',
        compactLogoPosition: 'left',
        navTextPosition: 'center',
        navTextOffset: 0,
        compactNavTextPosition: 'center',
        compactNavTextOffset: 0,
        showIcon: 'on',
        iconSize: 20 / 1440,
        textWidth: 300 / 1440,
        openPanelSize: 100,
        navTextWidth: 60 / 1440,
        gap: 12 / 1440,
        navGap: 64 / 1440,
        navPaddingLeft: 10 / 1440,
        navPaddingRight: 10 / 1440,
        textPaddingLeft: 10 / 1440,
        textPaddingRight: 10 / 1440,
        textPaddingTop: 10 / 1440,
        textPaddingBottom: 10 / 1440,
        fontSize: 16 / 1440,
        lineHeight: 16 / 1440,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        textAlign: 'center',
        openFontSize: 90 / 1440,
        openLineHeight: 16 / 1440,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        openTextAlign: 'center',
        compactPanelHeight: 30 / 1440,
        compactLogoMaxHeight: 20 / 1440,
        compactShowIcon: 'on',
        compactIconSize: 20 / 1440,
        compactNavTextWidth: 60 / 1440,
        compactNavGap: 20 / 1440,
        compactNavPaddingLeft: 10 / 1440,
        compactNavPaddingRight: 10 / 1440,
        compactFontSize: 16 / 1440,
        compactLineHeight: 16 / 1440,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
        compactTextAlign: 'center',
      },
    },
    layout: [
      '__componentName__',
      'link',
      'logo',
      'logoMaxHeight',
      'logoPosition',
      'panelHeight',
      'backgroundColor',
      'logoColor',
      'iconColor',
      'showIcon',
      'iconSize',
      'linkColor',
      'openLinkColor',
      'compactShowIcon',
      'compactIconColor',
      'compactLinkColor',
      'compactLogoColor',
      'compactBackgroundColor',
      'compactLogoMaxHeight',
      'compactLogoPosition',
      'compactPanelHeight',
      'compactIconSize',
      'compactNavTextWidth',
      'compactNavTextPosition',
      'compactNavTextOffset',
      'compactNavGap',
      'compactNavPaddingLeft',
      'compactNavPaddingRight',
      'compactFontFamily',
      'compactFontSettings',
      'compactFontSize',
      'compactLineHeight',
      'compactLetterSpacing',
      'compactWordSpacing',
      'compactTextAlign',
      'compactTextAppearance',
      'openLogoColor',
      'menuBackgroundColor',
      'overlayColor',
      'closeButtonColor',
      'effect',
      'textWidth',
      'navTextWidth',
      'navTextPosition',
      'navTextOffset',
      'position',
      'gap',
      'navGap',
      'navPaddingLeft',
      'navPaddingRight',
      'textPaddingLeft',
      'textPaddingRight',
      'textPaddingTop',
      'textPaddingBottom',
      'fontFamily',
      'fontSettings',
      'fontSize',
      'lineHeight',
      'letterSpacing',
      'wordSpacing',
      'textAlign',
      'textAppearance',
      'openFontFamily',
      'openFontSettings',
      'openFontSize',
      'openLineHeight',
      'openLetterSpacing',
      'openWordSpacing',
      'openTextAlign',
      'openTextAppearance',
    ],
  },
  panels: [
    {
      id: 'general',
      icon: 'settings',
      title: 'General',
      tooltip: 'General Settings',
      layout: [
        '__componentName__',
        'logo',
      ],
    },
    {
      id: 'default',
      icon: 'default',
      title: 'Default',
      tooltip: 'Default State',
      layout: defaultNavStateLayout,
    },
    {
      id: 'compact',
      icon: 'compact',
      title: 'Compact',
      tooltip: 'Compact State',
      layout: compactNavStateLayout,
      availableWhen: {
        navigationPosition: ['switch'],
      },
    },
    {
      id: 'open',
      icon: 'open',
      title: 'Open',
      tooltip: 'Open State',
      layout: openNavStateLayout,
    },
    {
      id: 'links',
      icon: 'content',
      title: 'Links',
      tooltip: 'Link Settings',
      layout: [
        '__componentName__',
        'link',
      ],
    },
  ],
  paletteBookmark: {
    items: [...paletteBookmarkItems],
    panelIds: ['default', 'compact', 'open'],
    stateItems: {
      default: ['iconColor', 'logoColor', 'linkColor', 'backgroundColor'],
      hover: ['iconColor', 'logoColor', 'linkColor'],
      compact: ['compactIconColor', 'compactLogoColor', 'compactLinkColor', 'compactBackgroundColor'],
      'compact-hover': ['compactIconColor', 'compactLogoColor', 'compactLinkColor'],
      open: ['closeButtonColor', 'openLogoColor', 'openLinkColor', 'menuBackgroundColor', 'overlayColor'],
      'open-hover': ['closeButtonColor', 'openLogoColor', 'openLinkColor'],
    },
  },
  states: ['default', 'hover'],
  statePanels: ['default', 'compact', 'open'],
} satisfies ComponentSchemaV1;

export const BurgerComponent = {
  element: Burger,
  id: 'basic-burger',
  name: 'Basic Burger',
  category: 'navigation',
  version: 1,
  preview: {
    type: 'image' as const,
    url: 'https://cdn.cntrl.site/component-assets/Simple Burger.png',
  },
  layoutMode: 'navigation' as const,
  defaultSize: {
    d: {
      width: '100%',
      height: 60 / 1440,
    },
    t: {
      width: '100%',
      height: 60 / 768,
    },
    m: {
      width: '100%',
      height: 56 / 375,
    },
  },
  defaultNavigationPosition: {
    d: 'switch',
    t: 'switch',
    m: 'stickyTop',
  } as const,
  schema,
  sourceCode: burgerSourceRaw,
  assetsPaths: {
    content: [],
    parameters: [{ path: 'logo.icon', placeholderEnabled: true }],
  },
  fontSettingsPaths: {
    content: [],
    parameters: [{ path: 'fontFamily' }, { path: 'openFontFamily' }, { path: 'compactFontFamily' }],
  },
  fontRelations: {
    fontSettings: 'fontFamily',
    openFontSettings: 'openFontFamily',
    compactFontSettings: 'compactFontFamily',
  },
};
