import { Burger } from './Burger';
import { ComponentSchemaV1 } from '../../types/SchemaV1';
import burgerSourceRaw from './Burger.tsx?raw';

function createRangeControlLayoutProperty(title: string) {
  return {
    type: 'number' as const,
    scope: 'layout' as const,
    title,
    min: 0,
    max: 100,
    display: { type: 'range-control' as const },
  };
}

const textStyleProperties = {
  fontSettings: {
    type: 'object' as const,
    display: { type: 'font-settings-weight', hideLabel: true, useTabDesign: true },
    properties: {
      fontWeight: { type: 'number' as const },
      fontStyle: { type: 'string' as const },
    },
  },
  fontSize: {
    type: 'number' as const,
    display: { type: 'font-size' },
  },
  lineHeight: {
    type: 'number' as const,
    display: { type: 'line-height-input' },
  },
  letterSpacing: {
    type: 'number' as const,
    display: { type: 'letter-spacing-input' },
  },
  wordSpacing: {
    type: 'number' as const,
    display: { type: 'word-spacing-input' },
  },
  textAlign: {
    type: 'string' as const,
    enum: ['left', 'center', 'right', 'justify'],
    display: { type: 'vertical-text-aligh-options' },
  },
  textAppearance: {
    type: 'object' as const,
    display: { type: 'text-appearance', useTabDesign: true },
    properties: {
      textTransform: { type: 'string' as const, enum: ['none', 'uppercase', 'lowercase', 'capitalize'] },
      textDecoration: { type: 'string' as const, enum: ['none', 'underline'] },
      fontVariant: { type: 'string' as const, enum: ['normal', 'small-caps'] },
    },
  },
};

function prefixedTextStyleKey(prefix: 'open' | 'compact' | '', name: string) {
  if (!prefix) return name;
  return `${prefix}${name.charAt(0).toUpperCase()}${name.slice(1)}`;
}

function createBurgerTextStyleProperties(prefix: 'open' | 'compact' | '') {
  return {
    [prefixedTextStyleKey(prefix, 'fontFamily')]: {
      type: 'string' as const,
      scope: 'common' as const,
      title: '',
      display: { type: 'font-family-select' as const, hideLabel: true, useTabDesign: true },
    },
    [prefixedTextStyleKey(prefix, 'fontSettings')]: {
      ...textStyleProperties.fontSettings,
      scope: 'common' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'fontSize')]: {
      ...textStyleProperties.fontSize,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'lineHeight')]: {
      ...textStyleProperties.lineHeight,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'letterSpacing')]: {
      ...textStyleProperties.letterSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'wordSpacing')]: {
      ...textStyleProperties.wordSpacing,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAlign')]: {
      ...textStyleProperties.textAlign,
      scope: 'layout' as const,
      title: '',
    },
    [prefixedTextStyleKey(prefix, 'textAppearance')]: {
      ...textStyleProperties.textAppearance,
      scope: 'layout' as const,
      title: '',
    },
  };
}

const closedTextStyleProperties = createBurgerTextStyleProperties('');
const openTextStyleProperties = createBurgerTextStyleProperties('open');
const compactTextStyleProperties = createBurgerTextStyleProperties('compact');

const defaultNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['logoMaxHeight', 'panelHeight'] },
  'logoPosition',
  { type: 'row' as const, items: ['iconSize', 'iconAnimation'] },
  'navTextWidth',
  'fontFamily',
  'fontSettings',
  { type: 'row' as const, items: ['fontSize', 'lineHeight', 'letterSpacing', 'wordSpacing'] },
  'textAlign',
  'textAppearance',
  'navGap',
  'navPaddingLeft',
  'navPaddingRight',
];

const compactNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['compactLogoMaxHeight', 'compactPanelHeight'] },
  'compactLogoPosition',
  { type: 'row' as const, items: ['compactIconSize', 'compactIconAnimation'] },
  'compactNavTextWidth',
  'compactFontFamily',
  'compactFontSettings',
  { type: 'row' as const, items: ['compactFontSize', 'compactLineHeight', 'compactLetterSpacing', 'compactWordSpacing'] },
  'compactTextAlign',
  'compactTextAppearance',
  'compactNavGap',
  'compactNavPaddingLeft',
  'compactNavPaddingRight',
];

const openNavStateLayout = [
  '__componentName__',
  { type: 'row' as const, items: ['textWidth'] },
  'effect',
  'position',
  'openFontFamily',
  'openFontSettings',
  { type: 'row' as const, items: ['openFontSize', 'openLineHeight', 'openLetterSpacing', 'openWordSpacing'] },
  'openTextAlign',
  'openTextAppearance',
];

const defaultTextAppearance = {
  textTransform: 'none',
  textDecoration: 'none',
  fontVariant: 'normal',
};

const defaultFontSettings = {
  fontWeight: 400,
  fontStyle: 'normal',
};

const POSITION_VALUES = [
  'left-top',
  'center-top',
  'right-top',
  'left-center',
  'center-center',
  'right-center',
  'left-bottom',
  'center-bottom',
  'right-bottom',
] as const;

const paletteBookmarkItems = [
  'iconColor',
  'logoColor',
  'closeButtonColor',
  'linkColor',
  'backgroundColor',
] as const;

const schema = {
  type: 'object',
  version: 1,
  settings: {
    sizing: 'auto manual',
    properties: {
      link: {
        type: 'array',
        scope: 'common',
        display: { type: 'page-url-link' },
        items: {
          type: 'object',
          properties: {
            mode: { type: 'string', enum: ['page', 'url'] },
            page: { type: 'string' },
            url: { type: 'string', message: 'Paste URL here...' },
            label: { type: 'string' },
            anchor: { type: 'string' },
            openIn: { type: 'string' },
            showIn: { type: 'string', enum: ['always', 'open only', 'open and compact', 'default and open'] },
          },
        },
      },
      socialLink: {
        type: 'array',
        scope: 'common',
        display: { type: 'url-list' },
        items: {
          type: 'string',
          message: 'Paste URL here...',
        },
      },
      logo: {
        type: 'object',
        scope: 'common',
        title: 'Logo',
        display: { type: 'button-icon-switch' },
        properties: {
          mode: {
            type: 'string',
            enum: ['On', 'Off'],
          },
          icon: {
            type: ['string', 'null'] as const,
            title: 'Logo',
            display: { type: 'settings-image-input' },
          },
        },
      },
      logoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Logo Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      logoPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Logo position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      compactLogoPosition: {
        type: 'string',
        scope: 'layout',
        title: 'Logo position',
        display: { type: 'toggle-cycle', enum: ['left', 'center', 'right'] },
      },
      logoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo',
        titleByState: {
          default: 'Logo',
          hover: 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      panelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      backgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'BG',
        display: { type: 'palette-color-picker' },
      },
      iconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon',
        titleByState: {
          default: 'Icon',
          hover: 'Icon Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      iconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Icon size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      iconAnimation: {
        type: 'string',
        scope: 'layout',
        title: 'Icon animation',
        display: { type: 'toggle-cycle', enum: ['a'] },
      },
      linkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Default',
        titleByState: {
          default: 'Link Default',
          hover: 'Link Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon',
        titleByState: {
          compact: 'Icon',
          'compact-hover': 'Icon Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactCloseButtonColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon close',
        titleByState: {
          compact: 'Icon close',
          'compact-hover': 'Icon close Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Compact',
        titleByState: {
          compact: 'Link Compact',
          'compact-hover': 'Link Compact Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactLogoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo',
        titleByState: {
          compact: 'Logo',
          'compact-hover': 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      compactBackgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'BG',
        display: { type: 'palette-color-picker' },
      },
      openLinkColor: {
        type: 'string',
        scope: 'common',
        title: 'Link Open',
        titleByState: {
          open: 'Link Open',
          'open-hover': 'Link Open Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      socialIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Social Default',
        titleByState: {
          default: 'Social Default',
          hover: 'Social Hover',
          compact: 'Social Compact',
          'compact-hover': 'Social Compact Hover',
          open: 'Social Open',
          'open-hover': 'Social Open Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      openLogoColor: {
        type: 'string',
        scope: 'common',
        title: 'Logo',
        titleByState: {
          open: 'Logo',
          'open-hover': 'Logo Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      menuBackgroundColor: {
        type: 'string',
        scope: 'common',
        title: 'Menu BG',
        display: { type: 'palette-color-picker' },
      },
      overlayColor: {
        type: 'string',
        scope: 'common',
        title: 'Overlay',
        display: { type: 'palette-color-picker' },
      },
      closeButtonColor: {
        type: 'string',
        scope: 'common',
        title: 'Icon close',
        titleByState: {
          default: 'Icon close',
          hover: 'Icon close Hover',
          open: 'Icon close',
          'open-hover': 'Icon close Hover',
        },
        display: { type: 'palette-color-picker' },
      },
      effect: {
        type: 'string',
        scope: 'layout',
        title: 'Effect',
        display: { type: 'toggle-cycle', enum: ['fade', 'left', 'top', 'right', 'bottom'] },
      },
      textWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Open text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      navTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      position: {
        type: 'string',
        scope: 'layout',
        title: 'Position',
        display: { type: 'toggle-cycle', enum: [...POSITION_VALUES] },
      },
      stateOverrides: {
        type: 'object',
        scope: 'common',
      },
      gap: createRangeControlLayoutProperty('Gap'),
      navGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      navPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      textPaddingLeft: createRangeControlLayoutProperty('Text padding left'),
      textPaddingRight: createRangeControlLayoutProperty('Text padding right'),
      textPaddingTop: createRangeControlLayoutProperty('Text padding top'),
      textPaddingBottom: createRangeControlLayoutProperty('Text padding bottom'),
      compactLogoMaxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Logo Max Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactPanelHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Height',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactIconSize: {
        type: 'number',
        scope: 'layout',
        title: 'Icon size',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactIconAnimation: {
        type: 'string',
        scope: 'layout',
        title: 'Icon animation',
        display: { type: 'toggle-cycle', enum: ['a'] },
      },
      compactNavTextWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Text width',
        display: { type: 'numeric-input' },
        min: 0,
        max: 9999,
      },
      compactNavGap: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav gap',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      compactNavPaddingLeft: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding left',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      compactNavPaddingRight: {
        type: 'number' as const,
        scope: 'layout' as const,
        title: 'Nav padding right',
        min: 0,
        max: 100,
        display: { type: 'range-control' as const, visible: false },
      },
      ...closedTextStyleProperties,
      ...openTextStyleProperties,
      ...compactTextStyleProperties,
    },
    defaults: {
      link: [
        { mode: 'page', page: '', url: '', label: 'Home', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'Works', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'About', anchor: '', openIn: 'Same Tab', showIn: 'always' },
        { mode: 'page', page: '', url: '', label: 'Contact', anchor: '', openIn: 'Same Tab', showIn: 'always' },
      ],
      socialLink: ['', '', '', ''],
      logo: {
        mode: 'On',
        icon: null,
      },
      backgroundColor: '#ffffff',
      logoColor: '#000000',
      iconColor: '#000000',
      linkColor: '#000000',
      openLinkColor: '#000000',
      compactIconColor: '#000000',
      compactCloseButtonColor: '#000000',
      compactLinkColor: '#000000',
      compactLogoColor: '#000000',
      compactBackgroundColor: '#ffffff',
      socialIconColor: '#000000',
      openLogoColor: '#000000',
      menuBackgroundColor: '#ffffff',
      overlayColor: 'rgba(0, 0, 0, 0.45)',
      closeButtonColor: '#000000',
      effect: 'fade',
      iconAnimation: 'a',
      logoPosition: 'left',
      compactLogoPosition: 'left',
      position: 'left-top',
      fontFamily: 'Goudy Bookletter 1911',
      fontSettings: defaultFontSettings,
      textAlign: 'left',
      openFontFamily: 'Goudy Bookletter 1911',
      openFontSettings: defaultFontSettings,
      openTextAlign: 'left',
      compactIconAnimation: 'a',
      compactFontFamily: 'Goudy Bookletter 1911',
      compactFontSettings: defaultFontSettings,
      compactTextAlign: 'left',
      stateOverrides: {
        hover: {
          linkColor: '#666666',
          socialIconColor: '#666666',
          iconColor: '#666666',
          logoColor: '#666666',
          closeButtonColor: '#666666',
        },
      },
    },
    displayRules: [
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoPosition.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoMaxHeight.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoPosition.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.logoColor.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.compactLogoColor.display.visible', value: false },
      },
      {
        if: { name: 'logo.mode', value: 'Off' },
        then: { name: 'properties.openLogoColor.display.visible', value: false },
      },
    ],
    layoutDefaults: {
      m: {
        position: 'left-top',
        panelHeight: 56 / 375,
        logoMaxHeight: 80 / 375,
        logoPosition: 'left',
        compactLogoPosition: 'left',
        iconSize: 16 / 375,
        textWidth: 240 / 375,
        navTextWidth: 120 / 375,
        gap: 24 / 375,
        navGap: 24 / 375,
        navPaddingLeft: 10 / 375,
        navPaddingRight: 10 / 375,
        textPaddingLeft: 10 / 375,
        textPaddingRight: 10 / 375,
        textPaddingTop: 10 / 375,
        textPaddingBottom: 10 / 375,
        fontSize: 16 / 375,
        lineHeight: 20 / 375,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 16 / 375,
        openLineHeight: 20 / 375,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        compactPanelHeight: 56 / 375,
        compactLogoMaxHeight: 80 / 375,
        compactIconSize: 16 / 375,
        compactNavTextWidth: 120 / 375,
        compactNavGap: 24 / 375,
        compactNavPaddingLeft: 10 / 375,
        compactNavPaddingRight: 10 / 375,
        compactFontSize: 16 / 375,
        compactLineHeight: 20 / 375,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
      },
      t: {
        position: 'left-top',
        panelHeight: 60 / 768,
        logoMaxHeight: 100 / 768,
        logoPosition: 'left',
        compactLogoPosition: 'left',
        iconSize: 16 / 768,
        textWidth: 260 / 768,
        navTextWidth: 140 / 768,
        gap: 32 / 768,
        navGap: 32 / 768,
        navPaddingLeft: 10 / 768,
        navPaddingRight: 10 / 768,
        textPaddingLeft: 10 / 768,
        textPaddingRight: 10 / 768,
        textPaddingTop: 10 / 768,
        textPaddingBottom: 10 / 768,
        fontSize: 16 / 768,
        lineHeight: 20 / 768,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        openFontSize: 16 / 768,
        openLineHeight: 20 / 768,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        compactPanelHeight: 60 / 768,
        compactLogoMaxHeight: 100 / 768,
        compactIconSize: 16 / 768,
        compactNavTextWidth: 140 / 768,
        compactNavGap: 32 / 768,
        compactNavPaddingLeft: 10 / 768,
        compactNavPaddingRight: 10 / 768,
        compactFontSize: 16 / 768,
        compactLineHeight: 20 / 768,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
      },
      d: {
        position: 'left-top',
        panelHeight: 40 / 1440,
        logoMaxHeight: 120 / 1440,
        logoPosition: 'left',
        compactLogoPosition: 'left',
        iconSize: 16 / 1440,
        textWidth: 60 / 1440,
        navTextWidth: 60 / 1440,
        gap: 12 / 1440,
        navGap: 12 / 1440,
        navPaddingLeft: 10 / 1440,
        navPaddingRight: 10 / 1440,
        textPaddingLeft: 10 / 1440,
        textPaddingRight: 10 / 1440,
        textPaddingTop: 10 / 1440,
        textPaddingBottom: 10 / 1440,
        fontSize: 16 / 1440,
        lineHeight: 16 / 1440,
        letterSpacing: 0,
        wordSpacing: 0,
        textAppearance: defaultTextAppearance,
        textAlign: 'center',
        openFontSize: 16 / 1440,
        openLineHeight: 16 / 1440,
        openLetterSpacing: 0,
        openWordSpacing: 0,
        openTextAppearance: defaultTextAppearance,
        openTextAlign: 'center',
        compactPanelHeight: 40 / 1440,
        compactLogoMaxHeight: 120 / 1440,
        compactIconSize: 16 / 1440,
        compactNavTextWidth: 60 / 1440,
        compactNavGap: 12 / 1440,
        compactNavPaddingLeft: 10 / 1440,
        compactNavPaddingRight: 10 / 1440,
        compactFontSize: 16 / 1440,
        compactLineHeight: 16 / 1440,
        compactLetterSpacing: 0,
        compactWordSpacing: 0,
        compactTextAppearance: defaultTextAppearance,
        compactTextAlign: 'center',
      },
    },
    layout: [
      '__componentName__',
      'link',
      'socialLink',
      'logo',
      'logoMaxHeight',
      'logoPosition',
      'panelHeight',
      'backgroundColor',
      'logoColor',
      'iconColor',
      'iconSize',
      'iconAnimation',
      'linkColor',
      'openLinkColor',
      'compactIconColor',
      'compactCloseButtonColor',
      'compactLinkColor',
      'compactLogoColor',
      'compactBackgroundColor',
      'compactLogoMaxHeight',
      'compactLogoPosition',
      'compactPanelHeight',
      'compactIconSize',
      'compactIconAnimation',
      'compactNavTextWidth',
      'compactNavGap',
      'compactNavPaddingLeft',
      'compactNavPaddingRight',
      'compactFontFamily',
      'compactFontSettings',
      'compactFontSize',
      'compactLineHeight',
      'compactLetterSpacing',
      'compactWordSpacing',
      'compactTextAlign',
      'compactTextAppearance',
      'socialIconColor',
      'openLogoColor',
      'menuBackgroundColor',
      'overlayColor',
      'closeButtonColor',
      'effect',
      'textWidth',
      'navTextWidth',
      'position',
      'gap',
      'navGap',
      'navPaddingLeft',
      'navPaddingRight',
      'textPaddingLeft',
      'textPaddingRight',
      'textPaddingTop',
      'textPaddingBottom',
      'fontFamily',
      'fontSettings',
      'fontSize',
      'lineHeight',
      'letterSpacing',
      'wordSpacing',
      'textAlign',
      'textAppearance',
      'openFontFamily',
      'openFontSettings',
      'openFontSize',
      'openLineHeight',
      'openLetterSpacing',
      'openWordSpacing',
      'openTextAlign',
      'openTextAppearance',
    ],
  },
  panels: [
    {
      id: 'general',
      icon: 'settings',
      title: 'General',
      tooltip: 'General Settings',
      layout: [
        '__componentName__',
        'logo',
        'logoPosition',
      ],
    },
    {
      id: 'default',
      icon: 'default',
      title: 'Default',
      tooltip: 'Default State',
      layout: defaultNavStateLayout,
    },
    {
      id: 'compact',
      icon: 'compact',
      title: 'Compact',
      tooltip: 'Compact State',
      layout: compactNavStateLayout,
      availableWhen: {
        navigationPosition: ['default', 'switch'],
      },
    },
    {
      id: 'open',
      icon: 'open',
      title: 'Open',
      tooltip: 'Open State',
      layout: openNavStateLayout,
    },
    {
      id: 'links',
      icon: 'content',
      title: 'Links',
      tooltip: 'Links Settings',
      layout: [
        '__componentName__',
        'link',
      ],
    },
    {
      id: 'socialLinks',
      icon: 'social',
      title: 'Social',
      tooltip: 'Social Links',
      layout: [
        '__componentName__',
        'socialLink',
      ],
    },
  ],
  paletteBookmark: {
    items: [...paletteBookmarkItems],
    panelIds: ['default', 'compact', 'open'],
    stateItems: {
      default: ['iconColor', 'logoColor', 'closeButtonColor', 'linkColor', 'backgroundColor'],
      hover: ['iconColor', 'logoColor', 'closeButtonColor', 'linkColor'],
      compact: ['compactIconColor', 'compactLogoColor', 'compactCloseButtonColor', 'compactLinkColor', 'compactBackgroundColor'],
      'compact-hover': ['compactIconColor', 'compactLogoColor', 'compactCloseButtonColor', 'compactLinkColor'],
      open: ['closeButtonColor', 'openLogoColor', 'openLinkColor', 'socialIconColor', 'menuBackgroundColor', 'overlayColor'],
      'open-hover': ['closeButtonColor', 'openLogoColor', 'openLinkColor', 'socialIconColor'],
    },
  },
  states: ['default', 'hover'],
  statePanels: ['default', 'compact', 'open'],
} satisfies ComponentSchemaV1;

export const BurgerComponent = {
  element: Burger,
  id: 'burger',
  name: 'Burger',
  category: 'dev',
  version: 1,
  layoutMode: 'navigation' as const,
  defaultSize: {
    d: {
      width: '100%',
      height: 60 / 1440,
    },
    t: {
      width: '100%',
      height: 60 / 768,
    },
    m: {
      width: '100%',
      height: 56 / 375,
    },
  },
  schema,
  sourceCode: burgerSourceRaw,
  assetsPaths: {
    content: [],
    parameters: [{ path: 'logo.icon' }],
  },
  fontSettingsPaths: {
    content: [],
    parameters: [{ path: 'fontFamily' }, { path: 'openFontFamily' }, { path: 'compactFontFamily' }],
  },
  fontRelations: {
    fontSettings: 'fontFamily',
    openFontSettings: 'openFontFamily',
    compactFontSettings: 'compactFontFamily',
  },
};
