import { LightboxJournal } from './LightboxJournal';
import { ComponentSchemaV1 } from '../../types/SchemaV1';
import lightboxJournalSourceRaw from './LightboxJournal.tsx?raw';

const defaultCloseIconUrl = 'https://cdn.cntrl.site/component-assets/Close.svg';

const textStyleProperties = {
  fontSettings: {
    type: 'object' as const,
    display: { type: 'font-settings-weight', visible: true },
    properties: {
      fontWeight: { type: 'number' as const },
      fontStyle: { type: 'string' as const },
    },
  },
  fontSize: {
    type: 'number' as const,
    display: { type: 'font-size' },
  },
  lineHeight: {
    type: 'number' as const,
    display: { type: 'line-height-input' },
  },
  letterSpacing: {
    type: 'number' as const,
    display: { type: 'letter-spacing-input' },
  },
  wordSpacing: {
    type: 'number' as const,
    display: { type: 'word-spacing-input' },
  },
};

const schema: ComponentSchemaV1 = {
  type: 'object',
  version: 1,
  settings: {
    properties: {
      cover: {
        type: 'string',
        scope: 'common',
        title: '',
        display: { type: 'settings-image-input' },
      },
      coverFit: {
        type: 'string',
        scope: 'common',
        title: 'Display',
        display: { type: 'toggle-cycle', enum: ['cover', 'fit'] },
      },
      maxHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Max Height',
        min: 0,
        max: 100,
        display: { type: 'percentage-input' },
      },
      maxWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Max Width',
        min: 0,
        max: 100,
        display: { type: 'percentage-input' },
      },
      imageGap: {
        type: 'number',
        scope: 'layout',
        title: 'Image Gap',
        min: 0,
        max: 200,
        display: { type: 'range-control', visible: false },
      },
      backgroundColor: {
        type: 'string',
        scope: 'layout',
        title: 'BG',
        display: { type: 'settings-color-picker' },
      },
      objectFit: {
        type: 'string',
        scope: 'common',
        title: 'Display',
        display: { type: 'toggle-cycle', enum: ['cover', 'fit'] },
      },
      closeIcon: {
        type: ['string', 'null'] as const,
        scope: 'common',
        title: '',
        display: { type: 'settings-image-input' },
      },
      closeIconMaxWidth: {
        type: 'number',
        scope: 'layout',
        title: 'Max Width',
        display: { type: 'full-width-input' },
        min: 0,
        max: 1,
      },
      closeIconColor: {
        type: 'string',
        scope: 'common',
        title: 'Fill Icon',
        display: { type: 'settings-color-picker' },
      },
      closeIconHoverColor: {
        type: 'string',
        scope: 'common',
        title: 'Hover Icon',
        display: { type: 'settings-color-picker' },
      },
      textMaxWidth: {
        type: 'string',
        scope: 'common',
        title: 'Max Width',
        display: { type: 'full-width-input' },
        min: 0,
        max: 1,
      },
      textTransition: {
        type: 'string',
        scope: 'common',
        title: 'Transition',
        display: { type: 'toggle-cycle', enum: ['none', 'fade'] },
      },
      titlesGap: {
        type: 'number',
        scope: 'layout',
        title: 'Titles Gap',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
      textCountGap: {
        type: 'number',
        scope: 'layout',
        title: 'Text / Count Gap',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
      countCloseGap: {
        type: 'number',
        scope: 'layout',
        title: 'Count / Close Gap',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
      fontFamily: {
        type: 'string',
        scope: 'common',
        title: 'Font family',
        display: { type: 'font-family-select' },
      },
      title1Color: {
        type: 'string',
        scope: 'common',
        title: 'Title 1',
        display: { type: 'palette-color-picker' },
      },
      title2Color: {
        type: 'string',
        scope: 'common',
        title: 'Title 2',
        display: { type: 'palette-color-picker' },
      },
      title3Color: {
        type: 'string',
        scope: 'common',
        title: 'Title 3',
        display: { type: 'palette-color-picker' },
      },
      title1FontSettings: {
        ...textStyleProperties.fontSettings,
        scope: 'common',
        title: 'Title 1',
      },
      title1FontSize: {
        type: 'number',
        scope: 'layout',
        title: 'Title 1 Font Size',
        display: { type: 'font-size' },
      },
      title1LineHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Title 1 Line Height',
        display: { type: 'line-height-input' },
      },
      title1LetterSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 1 Letter Spacing',
        display: { type: 'letter-spacing-input' },
      },
      title1WordSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 1 Word Spacing',
        display: { type: 'word-spacing-input' },
      },
      title1TextAppearance: {
        type: 'object',
        scope: 'layout',
        title: 'Title 1 Text Appearance',
        display: { type: 'text-appearance' },
      },
      title2FontSettings: {
        ...textStyleProperties.fontSettings,
        scope: 'common',
        title: 'Title 2',
      },
      title2FontSize: {
        type: 'number',
        scope: 'layout',
        title: 'Title 2 Font Size',
        display: { type: 'font-size' },
      },
      title2LineHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Title 2 Line Height',
        display: { type: 'line-height-input' },
      },
      title2LetterSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 2 Letter Spacing',
        display: { type: 'letter-spacing-input' },
      },
      title2WordSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 2 Word Spacing',
        display: { type: 'word-spacing-input' },
      },
      title2TextAppearance: {
        type: 'object',
        scope: 'layout',
        title: 'Title 2 Text Appearance',
        display: { type: 'text-appearance' },
      },
      title3FontSettings: {
        ...textStyleProperties.fontSettings,
        scope: 'common',
        title: 'Title 3',
      },
      title3FontSize: {
        type: 'number',
        scope: 'layout',
        title: 'Title 3 Font Size',
        display: { type: 'font-size' },
      },
      title3LineHeight: {
        type: 'number',
        scope: 'layout',
        title: 'Title 3 Line Height',
        display: { type: 'line-height-input' },
      },
      title3LetterSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 3 Letter Spacing',
        display: { type: 'letter-spacing-input' },
      },
      title3WordSpacing: {
        type: 'number',
        scope: 'layout',
        title: 'Title 3 Word Spacing',
        display: { type: 'word-spacing-input' },
      },
      title3TextAppearance: {
        type: 'object',
        scope: 'layout',
        title: 'Title 3 Text Appearance',
        display: { type: 'text-appearance' },
      },
      contentMarginTop: {
        type: 'number',
        scope: 'layout',
        title: 'Content margin top',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
      contentMarginLeft: {
        type: 'number',
        scope: 'layout',
        title: 'Content margin left',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
      contentMarginRight: {
        type: 'number',
        scope: 'layout',
        title: 'Content margin right',
        min: 0,
        max: 200,
        display: { type: 'range-control' },
      },
    },
    defaults: {
      cover: 'https://cdn.cntrl.site/component-assets/Control-slider-default-picture-1.png',
      coverFit: 'cover',
      objectFit: 'cover',
      closeIcon: defaultCloseIconUrl,
      closeIconColor: '#ffffff',
      closeIconHoverColor: '#cccccc',
      textTransition: 'fade',
      fontFamily: 'Arial',
      title1Color: '#ffffff',
      title2Color: '#ffffff',
      title3Color: '#ffffff',
      title1FontSettings: {
        fontWeight: 400,
        fontStyle: 'normal',
      },
      title1LetterSpacing: 0,
      title1WordSpacing: 0,
      title1TextAppearance: {
        textTransform: 'none',
        textDecoration: 'none',
        fontVariant: 'normal',
      },
      title2FontSettings: {
        fontWeight: 400,
        fontStyle: 'normal',
      },
      title2LetterSpacing: 0,
      title2WordSpacing: 0,
      title2TextAppearance: {
        textTransform: 'none',
        textDecoration: 'none',
        fontVariant: 'normal',
      },
      title3FontSettings: {
        fontWeight: 400,
        fontStyle: 'normal',
      },
      title3LetterSpacing: 0,
      title3WordSpacing: 0,
      title3TextAppearance: {
        textTransform: 'none',
        textDecoration: 'none',
        fontVariant: 'normal',
      },
    },
    layoutDefaults: {
      m: {
        imageGap: 0,
        maxHeight: 80,
        maxWidth: 80,
        textMaxWidth: 0.4,
        closeIconMaxWidth: 0.02,
        backgroundColor: 'rgba(28, 31, 34, 0.9)',
        contentMarginTop: 0,
        contentMarginLeft: 0,
        contentMarginRight: 0,
        titlesGap: 0.1,
        textCountGap: 0.02,
        countCloseGap: 0.02,
        title1FontSize: 0.02,
        title1LineHeight: 0.02,
        title2FontSize: 0.02,
        title2LineHeight: 0.02,
        title3FontSize: 0.02,
        title3LineHeight: 0.02,
      },
      d: {
        maxHeight: 80,
        maxWidth: 80,
        imageGap: 0,
        textMaxWidth: 0.4,
        closeIconMaxWidth: 0.02,
        backgroundColor: 'rgba(28, 31, 34, 0.9)',
        contentMarginTop: 0,
        contentMarginLeft: 0,
        contentMarginRight: 0,
        titlesGap: 0.1,
        textCountGap: 0.02,
        countCloseGap: 0.02,
        title1FontSize: 0.02,
        title1LineHeight: 0.02,
        title2FontSize: 0.02,
        title2LineHeight: 0.02,
        title3FontSize: 0.02,
        title3LineHeight: 0.02,
      },
    },
    layout: [
      '__componentName__',
      'maxWidth',
      'maxHeight',
      'imageGap',
      'titlesGap',
      'textCountGap',
      'countCloseGap',
      'objectFit',
      'contentMarginTop',
      'contentMarginLeft',
      'contentMarginRight',
    ],
  },
  panels: [
    {
      id: 'general',
      icon: 'settings',
      title: 'General',
      tooltip: 'General Settings',
      layout: [
        { type: 'row', items: ['__componentName__'] },
        { type: 'row', title: 'Image', items: ['maxWidth', 'maxHeight'] },
        { type: 'row', title: 'Text', items: ['textMaxWidth', 'textTransition'] },
        { type: 'row', title: 'Close icon', items: ['closeIcon', 'closeIconMaxWidth'] },
        { type: 'row', title: 'Cover Image', items: ['cover', 'coverFit'] },
      ],
    },
    {
      id: 'typeStyle',
      icon: 'text-icon',
      title: 'Type Style',
      tooltip: 'Typography',
      layout: [
        'fontFamily',
        {
          type: 'group',
          title: '',
          items: [
            'title1FontSettings',
            { type: 'row', items: ['title1FontSize', 'title1LineHeight', 'title1LetterSpacing', 'title1WordSpacing'] },
            'title1TextAppearance',
          ],
        },
        {
          type: 'group',
          title: '',
          items: [
            'title2FontSettings',
            { type: 'row', items: ['title2FontSize', 'title2LineHeight', 'title2LetterSpacing', 'title2WordSpacing'] },
            'title2TextAppearance',
          ],
        },
        {
          type: 'group',
          title: '',
          items: [
            'title3FontSettings',
            { type: 'row', items: ['title3FontSize', 'title3LineHeight', 'title3LetterSpacing', 'title3WordSpacing'] },
            'title3TextAppearance',
          ],
        },
      ],
    },
  ],
  paletteBookmark: {
    items: ['backgroundColor', 'title1Color', 'title2Color', 'title3Color', 'closeIconColor', 'closeIconHoverColor'],
    panelIds: ['general', 'typeStyle'],
  },
  content: {
    type: 'array',
    settings: {
      addItemFromFileExplorer: true,
    },
    items: {
      type: 'object',
      properties: {
        title1: {
          type: 'string',
          label: 'Title 1',
          placeholder: 'Add Title 1...',
          display: { type: 'text-input' },
        },
        title2: {
          type: 'string',
          label: 'Title 2',
          placeholder: 'Add Title 2...',
          display: { type: 'text-input' },
        },
        title3: {
          type: 'string',
          label: 'Title 3',
          placeholder: 'Add Title 3...',
          display: { type: 'text-input' },
        },
        images: {
          type: 'object',
          label: 'Images',
          max: 2,
          display: {
            type: 'media-list-input',
          },
          properties: {
            url: { type: 'string' },
            name: { type: 'string' },
            objectFit: { type: 'string', enum: ['cover', 'contain'] },
          },
          required: ['url', 'name'],
        },
      },
    },
    default: [
      {
        title1: 'Journal Entry 1',
        title2: 'summer vacation',
        title3: 'July 1978',
        images: [
          {
            url: 'https://cdn.cntrl.site/projects/01KM5KBNFNRT3D0JP64K5EY92A/articles-assets/01KQ7RZNCQFC3T744H0KX6R3FR.jpeg',
            name: '',
            objectFit: 'contain',
          },
          {
            url: 'https://cdn.cntrl.site/projects/01KM5KBNFNRT3D0JP64K5EY92A/articles-assets/01KQ7RZRTSS60YBFT6Y37ZX00T.jpeg',
            name: '',
            objectFit: 'contain',
          },
        ],
      },
      {
        title1: 'Journal Entry 2',
        title2: 'spring break',
        title3: 'March 1979',
        images: [
          {
            url: 'https://cdn.cntrl.site/projects/01KM5KBNFNRT3D0JP64K5EY92A/articles-assets/01KQ9M9YJPQ5JWKCHDEW5M1GJD.jpeg',
            name: '',
            objectFit: 'contain',
          },
          {
            url: 'https://cdn.cntrl.site/projects/01KM5KBNFNRT3D0JP64K5EY92A/articles-assets/01KQ7S04EHBXQS1T4KVAMZNZQM.jpeg',
            name: '',
            objectFit: 'contain',
          },
        ],
      },
      {
        title1: 'Journal Entry 3',
        title2: 'winter vacation',
        title3: 'January 1980',
        images: [
          {
            url: 'https://cdn.cntrl.site/projects/01KM5KBNFNRT3D0JP64K5EY92A/articles-assets/01KQ9M9YJPQ5JWKCHDEW5M1GJD.jpeg',
            name: '',
            objectFit: 'contain',
          },
        ],
      },
    ],
  },
};

export const LightboxJournalComponent = {
  element: LightboxJournal,
  id: 'lightbox-journal',
  name: 'Lightbox Journal',
  category: 'galleries',
  version: 1,
  defaultSize: {
    d: {
      width: 350,
      height: 350,
    },
    m: {
      width: 300,
      height: 350,
    },
  },
  preview: {
    type: 'image' as const,
    url: 'https://cdn.cntrl.site/component-assets/Journal.png',
  },
  schema,
  sourceCode: lightboxJournalSourceRaw,
  assetsPaths: {
    content: [{ path: 'images.url', placeholderEnabled: true }],
    parameters: [],
  },
  fontSettingsPaths: {
    content: [],
    parameters: [],
  },
};
